### ISSUE TITLE
slack or discord identifier override

### ISSUE THREAD

**Issue by ksurl** [containrrr/shoutrrr#152]
slack used to have the option to override the username, which also worked for discord when using slack and appending /slack on the discord webhook. 

Can shoutrrr support setting the username/identifier for discord and/or slack?

I had 1 webhook and different watchtower instances used different identifiers so I knew which host was being updated. I supposed the workaround for now is to create a webhook for each one so it can have a unique username. I ended up using the ?title= trick that i saw on the watchtower issues for discord title embed.

**Comment by piksel** [comment]
They both do. For discord you supply `?username=USER` (or rather `?title=TITLE&username=USER` because of the mentioned bug).

For Slack, you just prepend it to the token:
`slack://[botname@]token-a/token-b/token-c`

But note that slack officially doesn't support changing the name of the bot via the API anymore, but it still seems to work for some people.

**Comment by ksurl** [comment]
Ok. It isn't documented, so I'll submit a PR later for this

**Comment by piksel** [comment]
Which part? The discord username is merged into the shoutrrr/main but it hasn't been released yet.

**Comment by ksurl** [comment]
I see. I meant the documentation doesn't have this yet. but I guess if it's not a released feature yet then it shouldn't be.

**Comment by piksel** [comment]
The documentation for Discord should have been in the last release, but it was overlooked. And since the documentation is only updated when a new version is released, the live one doesn't include it. The Slack one only mentions this as `[BotName@]` in the [overview](https://containrrr.dev/shoutrrr/services/overview/), but Slack really ought to have it's own full documentation page.

**Comment by piksel** [comment]
Slack got "proper" override support in #179 and the discord docs have been updated. I'd say this can be closed now.
