### ISSUE TITLE
Change URL format for mattermost

### ISSUE THREAD

**Issue by simskij** [containrrr/shoutrrr#35]
Currently, the mattermost URL is segmented as:

```
mattermost://host/token/user/channel
```

to fit with the rest of the services, this would likely be preferrable:

```
mattermost://username:token@host/channel
```

Thoughts?

**Comment by amirschnell** [comment]
I agree, it is a good practice to have all services use the same URL format.
I will create a PR

**Comment by amirschnell** [comment]
I just found an issue here:
The username is optional, so setting the token to the password place is not ideal.
I suggest the following format: 
```
mattermsot://username@host/token/channel
```

**Comment by simskij** [comment]
I like suggestion 1 of yours 👍🏻

**Comment by piksel** [comment]
If I recall correctly, the password is automatically "censored" from printouts, but I don't know how important that is in this case...

**Comment by simskij** [comment]
> I just found an issue here:
> The username is optional, so setting the token to the password place is not ideal.
> I suggest the following format:
> 
> ```
> mattermsot://username@host/token/channel
> ```
> 
> or maybe:
> 
> ```
> mattermsot://username@host/token?channel=channel
> ```

Are you still looking to do this change, @amirschnell or would you rather have me do it? 😅

**Comment by amirschnell** [comment]
sorry to keep you waiting so long, I had a lot to do.
I just finished the PR

**Comment by simskij** [comment]
No worries! Just wanted to check if I could be of help! 😅

**Comment by simskij** [comment]
@amirschnell and @piksel, you agree on something 😅  I'm fine with both, even if `:token` might be the most coherent solution.

**Comment by piksel** [comment]
I thought so as well,  and it would better align with how the other services work. But then I looked at how the token is generated, and it's not really a credential per se, it's just the randomly generated name for a web hook. So as I see it `host/token` is the most logical choice.
I am unsure about the username though, as that is optional since it is used to override what user is sending the message, and not as a credential.
Having both channel and user as query parameters would also line them up with the `params` argument to `Send()`.

Sorry for making this suggestion when you are already done with the changes @amirschnell . Any thoughts?

**Comment by simskij** [comment]
I think mattermost://[__`username`__@]__`mattermost-host`__/__`token`__[/__`channel`__] makes sense. i'd argue that it's still a username, even though it's not part of the credential. let's settle for the content of the or for the time being.
