### ISSUE TITLE
Add support for InsecureSkipVerify to the generic webhook service

### ISSUE THREAD

**Issue by atgreen** [containrrr/shoutrrr#424]
In testing environments, it is often useful to skip cert validation.  It would be useful to add an "InsecureSkipVerify" parameter option to the generic service.

**Comment by piksel** [comment]
The main problem with that is that it marks the code as having security vulnerabilities in code scanning software, which creates hassles for consumers of the library. Instead, the goal is to add support for custom CAs (including self-signed ones), which allows for explicit trust instead of turning off a security feature (which might be accidentally done in a prod environment, causing actual security issues).

**Comment by atgreen** [comment]
I work very closely with a highly regulated industry (finance), where they scan every little thing that gets deployed, but I don't believe -- for instance -- curl was ever flagged just because it has the optional ability to not validate certs.  Custom CA support is definitely important but isn't really sufficient for all use cases (expired certs, for instance).

**Comment by piksel** [comment]
Either use http or fix the certificate issue. Adding the code to disable SSL verification flags the code as being vulnerable (exactly the same as setting CURLOPT_SSL_VERIFYPEER to 0 when using libcurl).

Refs:
https://cwe.mitre.org/data/definitions/295.html
https://owasp.org/www-project-top-ten/2017/A6_2017-Security_Misconfiguration.html

**Comment by atgreen** [comment]
Ok, I will close this ticket.  I still believe that there is value in this option for testing purposes.  Those scanners may flag the setting of CURLOPT_SSL_VERIFYPEER to 0, but the option still exists in the library for testing purposes -- not production.

**Comment by piksel** [comment]
The problem is that *our* library will be flagged as having that vulnerability, because we include code to disable a security feature. The fact that the user must opt in to using that code is not something that's easily detectable by static analysis (and perhaps shouldn't even be). 

If you wrote another library that *used* libcurl with that option, you would have the same problem. It's not that libcurl (or any other library) *has* insecure options, it's writing a library that *uses* insecure options of another library (go stdlib `http` / `crypto/tls` in our case) that causes the issue.
