### ISSUE TITLE
Pushover token missing from config URL

### ISSUE THREAD

**Issue by KeystoneJack** [containrrr/shoutrrr#56]
It seems that pushover service doesn't work. Following the documentation on how to use the CLI I entered:
`./shoutrrr send -u 'pushover://<MY_PUSHOVER_TOKEN>/<MY_PUSHOVER_USER_KEY>'  -m 'Hello World!'`
and it spits out `error invoking send: token missing from config URL%`.

I have tried swithing place with token and user-key but no luck. What am I missing?

**Comment by piksel** [comment]
Hello! Yeah, the documentation for pushover is not correct in the published documentation (which has been fixed, but it's not live since the documentation is generated on releases). You can view the updated documentation here:
https://github.com/containrrr/shoutrrr/blob/master/docs/services/pushover.md

I will release v0.2 to fix this pretty soon. Sorry for the inconvenience!

**Comment by KeystoneJack** [comment]
It's fine 😸 Thanks for the link, it works perfectly now!

Thanks a bunch!
