### ISSUE TITLE
Sending emails with broken config panics

### ISSUE THREAD

**Issue by andig** [containrrr/shoutrrr#84]
Sending email from/to gmail without proper configuration gives either:

    timeout 1

message on the console, or- though I cannot consistently reproduce this- panics:

    panic: send on closed channel

    goroutine 54 [running]:
    github.com/containrrr/shoutrrr/pkg/router.sendToService.func1(0xc00008e540, 0x203b760, 0xc00044fb30, 0xc000210080, 0x1d, 0xc000096018)
            /Users/andig/go/pkg/mod/github.com/containrrr/shoutrrr@v0.0.0-20200721140131-bafc331a1968/pkg/router/router.go:83 +0x7b
    created by github.com/containrrr/shoutrrr/pkg/router.sendToService
            /Users/andig/go/pkg/mod/github.com/containrrr/shoutrrr@v0.0.0-20200721140131-bafc331a1968/pkg/router/router.go:83 +0xda
    exit status 2

**Comment by andig** [comment]
After upgrading to the latest version I'm still seeing the timeout message, will continue watching for the panics.

**Comment by piksel** [comment]
Yeah, the panic is probably because of a bug in the Router. Go-routines and channels is a lot less obvious than most other go code.

**Comment by andig** [comment]
I can share the timeout, but currently not the crash. Does this help?

As for channels: always close on the sending side. If you need it, use a signaling channel to indicate close is needed. Closed channel will end range loop or trigger select.

**Comment by piksel** [comment]
The timeout is actually working as intended. Since no port is specified, it tries to send it on port `25` of `gmail.com` but that port is "filtered" (meaning it's not closed, but rather no response is sent when attempting to connect to it)

<details>

<summary>
<code>$ nmap -p 25 gmail.com</code>

</summary>

```
Starting Nmap 7.80 ( https://nmap.org ) at 2020-12-20 20:23 CET
Nmap scan report for gmail.com (216.58.211.5)
Host is up (0.0067s latency).
Other addresses for gmail.com (not scanned): 2a00:1450:400f:80d::2005
rDNS record for 216.58.211.5: muc03s13-in-f5.1e100.net

PORT   STATE    SERVICE
25/tcp filtered smtp
```

</details>

Unfortunately,  this doesn't explain the panic though, so I will have to look into the router logic to understand what is happening.
