### ISSUE TITLE
discord 2000 character limit

### ISSUE THREAD

**Issue by XoniBlue** [containrrr/shoutrrr#91]
using shoutrrr with watchtower and discord, the notification is capped by the 2000 character limit on discord.  is there a way to split the message to a manageable size?

**Comment by piksel** [comment]
Could you describe the use case for such long messages? It wouldn't be much effort to automatically split the messages and make several requests, but that would easily lead to bot spam. So a limit would have to be set in any case to prevent it from, let's say sending a gigabyte of data. 

There should probably at least be a way to trim the messages to the maximum amount of characters and add a "[...]" to the end.

**Comment by piksel** [comment]
The current plan is to move the message to rich embeds, which doesn't seem to impose such a limit. It will split every line into its own embed though, and that means only 10 lines would be supported. This behaviour should probably be toggleable though.

I still shudder at the thought of getting spammed with >2k messages though 😅

**Comment by piksel** [comment]
Turns out that the same 2k restriction applies to the rich embed content, and a total restriction of 6k for the combined embeds. 

<details>
<summary>So this is the limit of a Shoutrrr notification to discord</summary>

![image](https://user-images.githubusercontent.com/807383/104089085-296eb980-526c-11eb-94bb-63213a94a08e.png)

</details>

Should be enough?

**Comment by piksel** [comment]
Fixed in #108 , included in v0.4.0.
Discord service no longer errors when the message is too long. Instead it splits it into chunks and adds them as Embeds. If they still are too long it will trim the contents and add an ellipsis instead of just failing to send.
